### PR TITLE
force rails 3 and scan the entire project, not just the files with changes

### PR DESCRIPTION
**Pull request by jdoconnor**
@matl33t 
This fixes brakeman pronto for us... end goal will to be fixing pronto to pass options like a quaterback

### CODE REVIEW

**Comment by jdoconnor** [comment]
@srhaber @11mdlow

**Comment by 11mdlow** [comment]
:+1:

**Comment by matl33t** [comment]
how's this work? does this mean brakeman runs on all the code and comments on every vulnerability in the PR?

**Comment by jdoconnor** [comment]
matt, you are correct

**Pull request merged**
